/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3b4a47',
        'on-tertiary-fixed-variant': '#5f4100',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'on-tertiary': '#422c00',
        'on-surface': '#d4e4fa',
        'surface-container-high': '#1c2b3c',
        'error': '#ffb4ab',
        'primary-container': '#25e6d1',
        'on-primary-fixed-variant': '#005048',
        'primary-fixed': '#4bfbe6',
        'secondary-fixed-dim': '#c4c0ff',
        'outline': '#849490',
        'tertiary-container': '#ffc456',
        'tertiary': '#ffe7c2',
        'on-surface-variant': '#bacac6',
        'secondary-fixed': '#e3dfff',
        'surface-bright': '#2c3a4c',
        'on-secondary-fixed': '#120068',
        'inverse-primary': '#006a60',
        'secondary': '#c4c0ff',
        'surface-container-highest': '#273647',
        'on-tertiary-fixed': '#271900',
        'on-secondary-container': '#b5b0ff',
        'secondary-container': '#3b27ca',
        'on-secondary': '#2200a3',
        'on-tertiary-container': '#745100',
        'on-background': '#d4e4fa',
        'surface-dim': '#051424',
        'on-error-container': '#ffdad6',
        'surface-tint': '#09deca',
        'on-primary': '#003731',
        'background': '#051424',
        'on-primary-container': '#006359',
        'on-error': '#690005',
        'on-primary-fixed': '#00201c',
        'primary-fixed-dim': '#09deca',
        'tertiary-fixed': '#ffdea9',
        'surface-container-lowest': '#010f1f',
        'primary': '#81ffec',
        'on-secondary-fixed-variant': '#3823c8',
        'tertiary-fixed-dim': '#f7bd50',
        'error-container': '#93000a',
        'surface': '#051424',
        'surface-container': '#122131',
        'surface-container-low': '#0d1c2d',
        'surface-variant': '#273647',
        'brand-surface': '#11151D',
        ink: {
          950: '#07090D',
          900: '#11151D',
          850: '#122131',
          800: '#1c2b3c',
          700: '#273647',
          600: '#3b4a47',
          500: '#849490',
        },
        cyan: {
          DEFAULT: '#81ffec',
          400: '#81ffec',
          500: '#25e6d1',
          300: '#4bfbe6',
        },
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        xxl: '64px',
        'margin-mobile': '20px',
        md: '16px',
        unit: '4px',
        xl: '40px',
        xs: '4px',
        sm: '8px',
        gutter: '24px',
        'margin-desktop': '120px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter'],
        'label-caps': ['Inter'],
        'title-1-mobile': ['Inter'],
        headline: ['Inter'],
        'title-1': ['Inter'],
        'number-xl': ['Inter'],
        caption: ['Inter'],
        body: ['Inter'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-1-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        headline: ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-mobile': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'title-1': ['34px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'number-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        caption: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        body: ['17px', { lineHeight: '26px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
